### ISSUE TITLE
possible broken lab

### ISSUE THREAD

**Issue by dgalimi13** [learn-co-curriculum/rails-create-action-readme#22] opened 2021-06-25 17:51 UTC
i followed the readme carefully step by step but dont get the error message missing template. after clicking submit on the form nothing happens. i also get 

1) form shows a new form that submits content and redirects and prints out params
     Failure/Error: redirect_to post_path(@post)
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"show", :controller=>"posts", :id=>nil} missing required keys: [:id]

as an error but in the routes file it has resources posts

**Comment by ihollander** [comment] 2021-07-01 14:10
Thanks for raising this issue. I'm not able to reproduce this error, so I'm closing this issue. You can view the working version of this lab in the [solution branch](https://github.com/learn-co-curriculum/rails-create-action-readme/tree/solution) and compare your code. Best of luck!

**Closed as completed by ihollander** 2021-07-01 14:10 UTC
